Add the removal events and command changes (#38)
* Add the removal events and command changes

* Ensure the required settings for Apps are set before enabling a plugin

* Bump the version

* When an App is removed, removed it's logs as well

* Remove the accessors when an app is removed

* When removing an app, remove more things

* Improve the required setting check

* Fix the method checking for command being invalid

* Improve the custom require function, move it outside the compiler.
The reason for this is so that it can easily call itself and thus be reused. What was happening was an oversign, aka a bug, when an App had a file or class inside a folder and it referenced another module inside another folder.

Example: 'app/helpers/thing.ts' requires 'app/models/something.ts' then it would fail saying 'Error: Cannot find module ../models/something' when that should work.

* Fix the command getPreviews not working, I should have tested

* Improve the logging of the error messages

* Prevent the status from going over early on updates