Improve the custom require function, move it outside the compiler. The reason for this is so that it can easily call itself and thus be reused. What was happening was an oversign, aka a bug, when an App had a file or class inside a folder and it referenced another module inside another folder.
Example: 'app/helpers/thing.ts' requires 'app/models/something.ts' then it would fail saying 'Error: Cannot find module ../models/something' when that should work.